### PR TITLE
Ensure Polymer 3 Modulizer compatibility 

### LINKED ISSUE #6: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #6

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-element-mixin/7)

### CODE REVIEW

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-element-mixin/7#-:-L8WgFPlCKrqtxyVWYJX:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/basic.html, line 50 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-element-mixin/7#-L8XPh65NN8COnNWZ_Fw:-L8XPh65NN8COnNWZ_Fx:b-qnnp2u) ([raw file](https://github.com/vaadin/vaadin-element-mixin/blob/e9c753a474a86c6154dc2a82e2cc2033ffefe760/test/basic.html#L50)):*
> ```HTML
>         fixture('default');
>         // wait for usage statistics to load
>         setTimeout(done, 100);
> ```

BTW this is not clean, magic timeout value. Not a blocker, can fix later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-mixin/7)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-mixin/7#-:-L8XQ-2b8HICueCyzVdN:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-element-mixin/7#-:-L8XSEAUkQfjjjpH-WRP:bnfp4nl)*

**Pull request merged**
